<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0</TargetFrameworks>
		<!-- greater or equal to 0.50? -->
		<IsNetStandardCompatible
			Condition="$([System.Version]::Parse('$(SpectreConsoleVersionWithoutSuffix)').CompareTo($([System.Version]::Parse('0.50')))) &gt;= 0">true</IsNetStandardCompatible>
		<TargetFrameworks
			Condition=" '$(IsNetStandardCompatible)' == 'True'"
			>$(TargetFrameworks);net48</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing.XUnit" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeFix.Testing.XUnit" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="Polyfill">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Shouldly" />
		<PackageReference Include="xunit" />
		<PackageReference Include="xunit.runner.visualstudio">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Spectre.Verify.Extensions" />

		<PackageReference Include="Spectre.Console" />
		<PackageReference Include="Spectre.Console.Cli" />
		<PackageReference Include="Spectre.Console.Testing" />
	</ItemGroup>

	<ItemGroup>
		<!--<ProjectReference Include="..\JKToolKit.Spectre.AutoCompletion.Integrations\JKToolKit.Spectre.AutoCompletion.Integrations.csproj" />-->
		<ProjectReference Include="..\JKToolKit.Spectre.AutoCompletion\JKToolKit.Spectre.AutoCompletion.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Expectations\Help\Default_Without_Args_Additional.Output.verified.txt">
			<ParentFile>$([System.String]::Copy('%(FileName)').Split('.')[0])</ParentFile>
			<DependentUpon>%(ParentFile).cs</DependentUpon>
		</None>
		<None Update="Expectations\Help\Default_Greeter.Output.verified.txt">
			<ParentFile>$([System.String]::Copy('%(FileName)').Split('.')[0])</ParentFile>
			<DependentUpon>%(ParentFile).cs</DependentUpon>
		</None>
	</ItemGroup>

</Project>